name: CI
on: 
    push:
        branches: ["staging"]

jobs:
    deployment:
        environment: staging
        runs-on: ubuntu-22.04
        steps:
            - name: Deploy to VPS 
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD}}
                port: ${{ secrets.SERVER_PORT }}
                script: 
                    git clone https://github.com/toniismail12/be-pc-ipm-go.git
