name: CI
on:
  push:
    branches: ["staging"]

jobs:
  build-and-push:
    environment: staging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate .env
        run: |
          echo PORT=${{ vars.PORT }} >> .env

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.IMAGE_NAME }}:latest-and-mantul .

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ vars.IMAGE_NAME }}:latest-and-mantul

  deployment:
    needs: build-and-push
    environment: staging
    runs-on: ubuntu-22.04
    steps:
      - name: Setup in Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD}}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop $(docker ps -q --filter "publish=9001")
            docker rm $(docker ps -a -q --filter ancestor=${{ vars.IMAGE_NAME }}:latest-and-mantul)
            docker rmi ${{ vars.IMAGE_NAME }}:latest-and-mantul
            docker pull ${{ vars.IMAGE_NAME }}:latest-and-mantul
            docker run -d --restart=always -p 9001:9001 ${{ vars.IMAGE_NAME }}:latest-and-mantul