name: CI
on: 
    push:
        branches: ["staging"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Build Docker image
            run: |
              docker build -t toniismailz/api-pc-ipm:${{ github.sha }} .
    
    push:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Log in to Docker Hub
              run: docker login --username toniismailz --password-stdin
              env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
            - name: Push Docker image to Docker Hub
              run: |
                docker push toniismailz/api-pc-ipm:${{ github.sha }}

    deployment:
        needs: push
        environment: staging
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS 
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD}}
                port: ${{ secrets.SERVER_PORT }}
                script: 
                    whoami
                    docker stop api-pc-ipm || true && docker rm api-pc-ipm || true
                    docker pull toniismailz/${{ vars.IMAGE_NAME }}
                    docker run -d --restart=always -p 9001:9001 toniismailz/${{ vars.IMAGE_NAME }}